#pragma once

#include <pybind11/pybind11.h>

#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QBackingStore>
#include <QBitmap>
#include <QButtonGroup>
#include <QByteArray>
#include <QClipboard>
#include <QColor>
#include <QCursor>
#include <QDesktopWidget>
#include <QDockWidget>
#include <QEvent>
#include <QFlags>
#include <QFocusEvent>
#include <QGraphicsEffect>
#include <QGraphicsProxyWidget>
#include <QGraphicsScene>
#include <QGraphicsSceneContextMenuEvent>
#include <QGraphicsSceneHoverEvent>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsSceneWheelEvent>
#include <QGraphicsView>
#include <QIcon>
#include <QInputMethodEvent>
#include <QKeyEvent>
#include <QLayout>
#include <QLocale>
#include <QList>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMetaMethod>
#include <QMetaObject>
#include <QMouseEvent>
#include <QObject>
#include <QObjectList>
#include <QPaintEvent>
#include <QPoint>
#include <QPushButton>
#include <QRect>
#include <QRegion>
#include <QResizeEvent>
#include <QScreen>
#include <QSize>
#include <QSizePolicy>
#include <QStatusBar>
#include <QString>
#include <QStyle>
#include <QStyleOption>
#include <QStyleOptionFrame>
#include <QStyleOptionFrameV2>
#include <QStyleOptionFrameV3>
#include <QThread>
#include <QTimer>
#include <QToolBar>
#include <QVariant>
#include <QWidget>
#include <QWindow>
#include <Qt>
